# Generated by Django 3.0.7 on 2020-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200625_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
    ]
