# Generated by Django 3.0.7 on 2020-06-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
